os: Visual Studio 2015

platform:
  - x64

branches:
  only:
  - master

version: '{build}-{branch}'

cache:
  - "node_modules"
  - "%LOCALAPPDATA%\\Yarn"

init:
  - cmd: echo 🚦 Authorizing Build
  - ps: if ($env:OS -eq "Windows_NT" -And $env:DEPLOY_WINDOWS -eq "0") { $host.SetShouldExit(0) }
  - cmd: git config --global core.autocrlf input

install:
  - cmd: echo 🔧 Setting up Node
  - ps: Install-Product node 9
  - cmd: npm --global update npm
  - cmd: npm --global install yarn

before_build:
  - cmd: echo 📥 Installing Dependencies
  - cmd: yarn install

build_script:
  - cmd: echo 📦 Building
  - cmd: npm run build --metadata

deploy_script:
  - cmd: echo 📮 Deploying to GitHub
  - cmd: npm run deploy

artifacts:
  - path: build\output\*.exe

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/a1a9de50af1c703bfe6c
    method: GET
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true

test: off
